language: android

jdk:
  oraclejdk7

env:
  global:
    - ANDROID_SDK_VERSION="r24.0.2"
    - BUILD_TOOLS="23.0.1"
    - TARGET_API="23"

android:
  components:
    - build-tools-${BUILD_TOOLS}  # specify build tools version as they might not be pre-installed
    - android-${TARGET_API}  # The SDK version used to compile your project

    # Additional components
    - extra-android-m2repository
    - extra-android-support

before_install:
  # environment info
  - uname -a

  # for gradle output style
  - export TERM=dumb

# Let's try to build...
install:
  ./gradlew clean build

script:
  ./gradlew check
